name: build .exe

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install --no-cache-dir --prefer-binary -r requirements.txt
      - run: ui/make.bat
      - uses: Nuitka/Nuitka-Action@v1.3
        with:
          script-name: gui.py
          msvc: latest
          mode: standalone
          output-file: nat-tool.exe
          windows-console-mode: disable
          nofollow-import-to: |
            _asyncio
            _bz2
            _ctypes
            _decimal
            _hashlib
            _lzma
            _multiprocessing
            _queue
            _ssl
            _wmi
            pyexpat
          enable-plugins: pyside6
          noinclude-qt-plugins: |
            iconengines
            imageformats
            tls
#      - uses: actions/upload-artifact@v4
#        with:
#          name: nat-tool
#          path: build/gui.dist/
      - uses: thedoctor0/zip-release@0.7.6
        with:
          filename: nat-tool.zip
          path: build/gui.dist/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: nat-tool.zip
