name: Build Nuitka EXE

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - uses: Nuitka/Nuitka-Action@v1.3
        with:
          script-name: gui.py
          msvc: latest
          mode: standalone
          windows-console-mode: disable
          nofollow-import-to: |
            _asyncio
            _bz2
            _ctypes
            _decimal
            _hashlib
            _lzma
            _multiprocessing
            _queue
            _ssl
            _wmi
            pyexpat
          enable-plugins: pyside6
          noinclude-qt-plugins: |
            iconengines
            imageformats
            tls
      - uses: actions/upload-artifact@v4
        with:
          name: exe
          path: gui.exe
